### ISSUE TITLE
Eval Error

### ISSUE THREAD

**Issue by VR2211** [Devangend/Discord.js-v13-Handler#2]
Hello,

I was about to test the eval command and i get this error,
```/home/container/Commands/Developer/eval.js:44
            let errorembed = new Discord.MessageEmbed()
                             ^
ReferenceError: Discord is not defined
    at Object.run (/home/container/Commands/Developer/eval.js:44:30)
    at module.exports (/home/container/Events/messageCreate.js:53:17)
    at Client.<anonymous> (/home/container/Handlers/Events.js:9:53)
    at Client.emit (node:events:390:28)
    at MessageCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/MessageCreate.js:26:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:351:31)
    at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/container/node_modules/ws/lib/event-target.js:199:18)
Node.js v17.1.0
```

What cloud be the problem and want can l do to fix it.

**Comment by VR2211** [comment]
It look like i fix it by added 


```const Discord = require('discord.js');```

At the top of the code

**Comment by Devangend** [comment]
alright got it.
